version: "3.3"
services:
  bokeh_serve_all:
    build: .
    image: bdslab/beehive:latest
    volumes:
      - "../data:/beehive/data"
    ports: 
      - "5009:5009"
    command: "bokeh serve --port 5009 --allow-websocket-origin=* bokeh/quadrant_plot/ \
                bokeh/volcano_plot/ \
                bokeh/scatter_expression/ \
                bokeh/gene_expression/ \
                bokeh/hexbin_expression/"
    
