

FAVORITE_GENES = '''
     APOE APP PSEN1 PSEN2 CLU GFAP PLP1
     BIN1 SORL1 ABCA7 CR1 CD33 MS4A
     PICALM EPHA1 INPPD5 MEF2C ADAM10
     AKAP4 MEG3'''.lower().split()

NOT_FAVORITE_GENES = '''
     MALAT1 '''.split()
